repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: detect-private-key
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: [ ]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-tidy-imports
        args: [ --statistics, --extend-ignore=F401 ]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ --safe ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ -r ]
        require_serial: true

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint

#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v2.5.1
#    hooks:
#      - id: prettier
#        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
#  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#    rev: v0.1.0
#    hooks:
#      - id: dockerfilelint
#  - repo: https://github.com/pre-commit/mirrors-eslint
#    rev: v8.22.0 # Use the sha / tag you want to point at
#    hooks:
#      - id: eslint
#        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
#        types: [file]
#        additional_dependencies:
#          - eslint@4.15.0
#          - eslint-config-google@0.7.1
#          - eslint-loader@1.6.1
#          - eslint-plugin-react@6.10.3
#          - babel-eslint@6.1.2
#          - eslint-plugin-jest@latest
#  - repo: https://github.com/PyCQA/pylint
#    rev: v2.12.2
#    hooks:
#      - id: pylint
#  - repo: https://github.com/pycqa/pydocstyle
#    rev: 6.1.1
#    hooks:
#      - id: pydocstyle
#        additional_dependencies: [ "toml" ]
#  - repo: https://github.com/asottile/reorder_python_imports
#    rev: 2.6.0
#    hooks:
#      - id: reorder_python_imports
#        args: [
#          --py22-plus, # nested_scopes
#          --py23-plus, #: generators
#          --py26-plus, #: with_statement
#          --py3-plus, #: division, absolute_import, print_function, unicode_literals
#          --py37-plus, #: generator_stop
#        ]
