#default_language_version:
#  python: python3.9
default_stages: [ commit ]
files: '^(investai/)|(extra/)|(thesis/)|(.github/workflows/.*.yml)|(.vim/)$'
#exclude: '^(venv.*/)|(env/)|(\.pytest_caches/)|(third_party/)|(.*__pycache__.*/)|()'
fail_fast: false
minimum_pre_commit_version: '0'
repos:
    ##########################################################################################
    # Meta hooks
    ##########################################################################################
    -   repo: meta
        hooks:
            #      - id: check-hooks-apply
            -   id: check-useless-excludes
            -   id: identity

    ##########################################################################################
    # Local hooks
    ##########################################################################################
    #  - repo: local
    #    hooks:
    #      - id: pytest-check
    #        name: pytest-check
    #        entry: bash -c "export PYTHONPATH='$PWD/venv/bin/python3'"
    #        language: system
    #        pass_filenames: true
    #        types: [ python ]

    -   repo: local
        hooks:
            -   id: pytest-check
                stages: [ push ]
                name: pytest
                entry: pytest --no-summary -q -n 7
                language: system
                pass_filenames: false
                always_run: true

    -   repo: local
        hooks:
            -   id: create-requirements_for_workflows.txt
                stages: [ commit ]
                name: Create requirements_for_workflows.txt
                # "if" just to make sure that on the GitHub we don't run this hook
                entry: bash -c "if [ -d venv ]; then ./start.sh -prfw; fi"
                language: system
                pass_filenames: false
                always_run: true


    ##########################################################################################
    # Pipeline hooks
    ##########################################################################################
    #  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    #    rev: v0.6 # Ensure this is the latest tag, comparing to the Releases tab
    #    hooks:
    #      - id: circleci_validate
    #        files: ^(.circleci/.*.yml)$

    -   repo: https://github.com/python-jsonschema/check-jsonschema
        rev: 0.21.0
        hooks:
            -   id: check-github-workflows
                files: ^(.github/workflows/.*.yml)$


    ##########################################################################################
    # Standard hooks
    ##########################################################################################
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            -   id: check-added-large-files
                types: [ file ]
                args: [ '--maxkb=1000' ]
            -   id: check-ast
            -   id: check-case-conflict
            -   id: check-byte-order-marker
            -   id: check-builtin-literals
            -   id: check-docstring-first
            -   id: check-executables-have-shebangs
            -   id: check-json
                files: \.json$ # TODO: fixme
            -   id: pretty-format-json
                files: \.json$ # TODO: fixme
                args:
                    - "--autofix"
                    - "--indent=4"
                    - "--no-sort-keys"
            -   id: check-merge-conflict
            #      - id: check-symlinks
            -   id: check-toml
            -   id: check-vcs-permalinks
            #      - id: check-xml
            -   id: debug-statements
            -   id: detect-aws-credentials
                args: [ --allow-missing-credentials ]
            -   id: detect-private-key
            -   id: end-of-file-fixer
            #      - id: file-contents-sorter
            -   id: fix-byte-order-marker
            -   id: fix-encoding-pragma
            #      - id: forbid-new-submodules
            -   id: mixed-line-ending
            #      - id: name-tests-test
            -   id: requirements-txt-fixer
            #      - id: sort-simple-yaml
            -   id: trailing-whitespace

    ##########################################################################################
    # Python
    ##########################################################################################
    #    -   repo: https://github.com/pycqa/isort
    #        rev: 5.12.0
    #        hooks:
    #            -   id: isort
    #                name: isort
    #    -   repo: https://github.com/psf/black
    #        rev: 23.1.0
    #        hooks:
    #            -   id: black
    #                name: black
    -   repo: https://github.com/pre-commit/mirrors-autopep8
        rev: v2.0.2
        hooks:
            -   id: autopep8
    -   repo: https://github.com/myint/autoflake
        rev: 'v2.0.0'
        hooks:
            -   id: autoflake
                args: [ '--in-place', '--remove-all-unused-imports' ]
                name: autoflake
    -   repo: https://github.com/charliermarsh/ruff-pre-commit
        rev: 'v0.0.201'
        hooks:
            -   id: ruff
                args: [ "--fix" ]
                name: ruff

    ##########################################################################################
    # Markdown
    ##########################################################################################
    -   repo: https://github.com/jumanjihouse/pre-commit-hooks
        rev: 3.0.0
        hooks:
            -   id: markdownlint
                files: \.(md|mdown|markdown)$
    #        files: ^README.md$

    ##########################################################################################
    # Latex
    ##########################################################################################
    -   repo: https://github.com/cmhughes/latexindent.pl
        rev: V3.19
        hooks:
            -   id: latexindent
                #        args: [ --yaml=.indentconfig.yaml ]
                files: docs/
    -   repo: https://github.com/jonasbb/pre-commit-latex-hooks
        rev: v1.3.0
        hooks:
            -   id: american-eg-ie
                files: docs/
            -   id: cleveref-capitalization
                files: docs/
            -   id: consistent-spelling
                files: docs/
                args:
                  [
                      "--emph=et al.",
                      "--emph=a priori",
                      "--emph=a posteriori",
                      '--regex=naive=\bna(i|\\"i)ve',
                  ]
            -   id: csquotes
                files: docs/
                #      - id: ensure-labels-for-sections # TODO (fixme): produce error
            -   id: no-space-in-cite
                files: docs/
            -   id: tilde-cite
                files: docs/
            -   id: unique-labels
                files: docs/


    ##########################################################################################
    # EditorConfig
    ##########################################################################################
    -   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
        rev: 2.6.1
        hooks:
            -   id: editorconfig-checker
                language: python
                files: ^(ai_investing/|docs/)
                exclude: (enplain.bst|project_info.tex|fitthesis.cls|\.py|\.ipynb|\.bib)$

    ##########################################################################################
    # Git
    ##########################################################################################
    -   repo: https://github.com/compilerla/conventional-pre-commit
        rev: v2.1.1
        hooks:
            -   id: conventional-pre-commit
                stages: [ commit-msg ]
                args: [ ]

    ##########################################################################################
    # Dockerfile
    ##########################################################################################
#    FIXME:
#    -   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#        rev: v0.1.0
#        hooks:
#            -   id: dockerfilelint
