program: investai/run/portfolio_allocation/train/train.py
method: random
commad:
    --wandb-sweep
    --algorithms ppo
    --project-verbose=1
    --total-timesteps=1000

metric:
    goal: minimize
    name: train/loss
parameters:
    policy:
        values:
            - MlpPolicy
    #        - CnnPolicy
    #        - MultiInputPolicy
    learning-rate:
        min: 0.0001
        max: 0.01
    n-steps:
        values:
            - 32
            - 64
            - 128
            - 256
            - 512
            - 1024
            - 2048
    gamma:
        min: 0.9
        max: 0.999
    gae-lambda:
        min: 0.8
        max: 0.999
    ent-coef:
        min: 0.0001
        max: 0.01
    vf-coef:
        min: 0.0001
        max: 0.01
    max-grad-norm:
        min: 0.5
        max: 0.99
    rms-prop-eps:
        min: 0.0001
        max: 0.01
    # 'use-rms-prop': bool,
    # 'use-sde': bool,
    sde-sample-freq:
        min: 4
        max: 32
    # 'normalize-advantage': bool,
    # 'tensorboard-log': Optional,
    # 'policy-kwargs': Optional,
    # 'verbose': int,
    # 'seed': Optional,
    # 'device': Union,
    # '-init-setup-model': bool,
    batch-size:
        values:
            - 32
            - 64
            - 128
            - 256
            - 512
    n-epochs:
        min: 1
        max: 10
    clip-range:
        min: 0.1
        max: 0.3
    clip-range-vf:
        values:
            - null
            - 0.05
            - 0.1
            - 0.15
            - 0.2
    target-kl:
        min: 0.01
        max: 0.05
    buffer-size:
        values:
            - 1000
            - 2000
            - 3000
            - 4000
            - 5000
    learning-starts:
        min: 100
        max: 1000
    tau:
        min: 0.001
        max: 0.01
    train-freq:
        min: 1
        max: 4
    gradient-steps:
        min: 1
        max: 4
    # 'action-noise': Optional,
    # 'replay-buffer-class': Optional,
    # 'replay-buffer-kwargs': Optional,
    # 'optimize-memory-usage': bool,
    target-update-interval:
        min: 1
        max: 4
    target-entropy:
        min: 0.1
        max: 0.2
    # 'use-sde-at-warmup': bool,
    policy-delay:
        min: 1
        max: 4
    target-policy-noise:
        min: 0.1
        max: 0.2
    target-noise-clip:
        min: 0.1
        max: 0.2
    exploration-fraction:
        min: 0.1
        max: 0.2
    exploration-initial-eps:
        min: 0.1
        max: 0.2
    exploration-final-eps:
        min: 0.1
        max: 0.2
