version: 2.1

jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run:
          name:
          command: |
            sudo pip3 install pre-commit
            pre-commit run --all-files

  latex:
    docker:
      - image: koppor/texlive
    steps:
      - checkout
      - run: 'make -C docs'
      - store_artifacts:
          path: output/
          destination: output

workflows:
  push:
    jobs:
      - lint
      - latex
