version: 2.1

on: [ push, pull_request, pull, fork ]

defaults:
  run:
    working-directory: .
    shell: bash

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - checkout
      - run:
          name: Pre-commit Checks
          command: |
            sudo pip3 install pre-commit
            pre-commit run --all-files

  documentation-build:
    docker:
      - image: koppor/texlive
    steps:
      - checkout
      - run: 'cd thesis && make'
      - store_artifacts:
          path: output/
          destination: output

workflows:
  push:
    jobs:
      - lint
#      - latex:
#          requires:
#            - lint
