#on: [ 'push', 'pull_request', 'pull', 'fork' ]

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: .
    shell: bash

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pre-commit
        run: |
          echo $PWD
          python3 -m pip install --upgrade pip
          pip3 install pre-commit
          pre-commit run --all-files --show-diff-on-failure
          echo $?

  documentation-build:
    runs-on: ubuntu-latest
    container:
      image: koppor/texlive
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build documentation
        run: |
          echo $PWD
          cd thesis
          echo $PWD
          make
