name: Foo

on:
  push:
    branches: [main, prod, new_feature]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing actions
        working-directory: .
        run: |
          python -m venv venv
          python main.py
