name: pytest

on: [ push, pull_request ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip3 install -r requirements_for_workflows.txt
      - name: Run pytest
        run: pytest
